# Generated by Django 5.2.13 on 2026-05-10 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email сотрудника')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('used', models.BooleanField(default=False, verbose_name='Использовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('conducted', 'Проведено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('event_type', models.CharField(choices=[('lecture', 'Лекция / Беседа'), ('practical', 'Практическое занятие'), ('quiz', 'Викторина / Конкурс'), ('parent_meeting', 'Родительское собрание'), ('briefing', 'Инструктаж'), ('action', 'Акция / Рейд'), ('excursion', 'Экскурсия'), ('training', 'Тренинг'), ('other', 'Иное')], default='lecture', max_length=30, verbose_name='Тип мероприятия')),
                ('location_type', models.CharField(choices=[('school', 'Школа (актовый зал, класс)'), ('street', 'Улица / Пешеходный переход'), ('autotown', 'Автогородок'), ('online', 'Онлайн'), ('other', 'Иное место')], default='school', max_length=20, verbose_name='Тип места')),
                ('tags', models.CharField(blank=True, help_text='Введите теги через запятую', max_length=500, null=True, verbose_name='Теги')),
                ('responsible_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответственное лицо')),
                ('location_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место проведения')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('report_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на отчет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization', verbose_name='Организация-проводитель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время ДТП')),
                ('location_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('severity', models.CharField(choices=[('light', 'Легкое'), ('medium', 'Среднее'), ('heavy', 'Тяжелое'), ('fatal', 'Смертельное')], default='light', max_length=20, verbose_name='Тяжесть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organization', verbose_name='Связанная организация')),
            ],
            options={
                'verbose_name': 'ДТП',
                'verbose_name_plural': 'ДТП',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='events.event')),
            ],
            options={
                'verbose_name': 'Файл отчета',
                'verbose_name_plural': 'Файлы отчетов',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('organization', 'Представитель организации'), ('propaganda', 'Сотрудник пропаганды')], default='organization', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('yuid_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название ЮИД-отряда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.organization', verbose_name='Организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('target_count', models.IntegerField(default=1, verbose_name='Плановое количество мероприятий')),
                ('completed_count', models.IntegerField(default=0, verbose_name='Выполнено мероприятий')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'План мероприятий',
                'verbose_name_plural': 'Планы мероприятий',
                'unique_together': {('year', 'month', 'organization')},
            },
        ),
    ]
