# Generated by Django 5.2.13 on 2026-05-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='effectiveness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Эффективность'),
        ),
    ]
