# Generated by Django 5.2.13 on 2026-05-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_effectiveness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='effectiveness',
        ),
    ]
