# Generated by Django 5.2.13 on 2026-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_effectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
    ]
