# Generated by Django 5.2.13 on 2026-05-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_organization_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gibdd_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждено ГИБДД'),
        ),
    ]
