# Generated by Django 5.2.13 on 2026-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_gibdd_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_uses',
            field=models.IntegerField(default=1, verbose_name='Максимум использований'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='Использовано раз'),
        ),
    ]
