# Generated by Django 5.2.13 on 2026-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_invitation_options_invitation_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='cluster_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Хеш кластера'),
        ),
    ]
