# Generated by Django 5.2.13 on 2026-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_accident_cluster_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('conducted', 'Проведено'), ('cancelled', 'Отменено'), ('approved', 'Подтверждено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
