# Generated by Django 5.2.13 on 2026-05-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_userprofile_email_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='onfirmation_code',
        ),
    ]
