# Generated by Django 5.2.13 on 2026-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_userprofile_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('organization', 'Представитель организации'), ('propaganda', 'Сотрудник пропаганды'), ('admin', 'Администратор')], default='organization', max_length=20),
        ),
    ]
