# Generated by Django 5.2.13 on 2026-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Теги'),
        ),
    ]
