# Generated by Django 5.2.13 on 2026-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_accident_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Теги'),
        ),
    ]
