from django.urls import path
from . import views
from .admin_views import *
from .views import *

urlpatterns = [
    path("", views.dashboard, name="home"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("map/", views.map_view, name="map"),
    path("delete/<int:event_id>/", views.delete_event, name="delete_event"),
    path("debug-session/", views.debug_session, name="debug_session"),
    path("api/event/<int:event_id>/json/", views.get_event_json, name="get_event_json"),
    path(
        "api/event/<int:event_id>/update/",
        views.update_event_json,
        name="update_event_json",
    ),
    path("api/search-by-inn/", views.search_organization_by_inn, name="search_by_inn"),
    path(
        "api/search-organizations/",
        views.search_organizations,
        name="search_organizations",
    ),
    path('api/delete-file/<int:file_id>/', views.delete_report_file, name='delete_report_file'),
    path('export-accidents/', views.export_accidents_excel, name='export_accidents'),
    path('upload/', views.upload_accidents, name='upload_accidents'),
    path('export-events/', views.export_events_excel, name='export_events'),
    path('api/ml-recommend/', views.ml_recommendation, name='ml_recommend'),
    path('calendar/', views.plan_calendar, name='plan_calendar'),
    path('admin-panel/', admin_dashboard, name='admin_dashboard'),
    path('admin-panel/schools/', admin_schools, name='admin_schools'),
    path('admin-panel/users/', admin_users, name='admin_users'),
    path('admin-panel/events/', admin_events, name='admin_events'),
    path('admin-panel/accidents/', admin_accidents, name='admin_accidents'),
    path('admin-panel/add-school/', admin_add_school, name='admin_add_school'),
    path('admin-panel/edit-school/', admin_edit_school, name='admin_edit_school'),
    path('admin-panel/delete-school/', admin_delete_school, name='admin_delete_school'),
    path('admin-panel/add-user/', admin_add_user, name='admin_add_user'),
    path('admin-panel/edit-user/', admin_edit_user, name='admin_edit_user'),
    path('admin-panel/delete-user/', admin_delete_user, name='admin_delete_user'),
    path('admin-panel/edit-event/', admin_edit_event, name='admin_edit_event'),
    path('admin-panel/delete-event/', admin_delete_event, name='admin_delete_event'),
    path('admin-panel/edit-accident/', admin_edit_accident, name='admin_edit_accident'),
    path('admin-panel/delete-accident/', admin_delete_accident, name='admin_delete_accident'),
    path('admin-panel/invitations/', admin_invitations, name='admin_invitations'),
    path('register/invite/<str:token>/', register_by_invite, name='register_by_invite'),
    path('api/clustered-accidents/', get_clustered_accidents, name='clustered_accidents'),
    path('api/accidents-by-month/', accidents_by_month, name='accidents_by_month'),
    path('api/accidents-by-months/', accidents_by_months, name='accidents_by_months'),
    path('api/event/<int:event_id>/approve/', approve_event, name='approve_event'),
    path('api/update-accidents-districts/', update_accidents_districts, name='update_accidents_districts'),
    path('train-model/', views.train_model_view, name='train_model'),
    path('school/<int:school_id>/analysis/', views.school_analysis, name='school_analysis'),
    path('gibdd-summary/', views.gibdd_summary_view, name='gibdd_summary'),
    path('api/school-analysis/', views.api_school_analysis, name='api_school_analysis'),
    path('ml-analysis/', views.ml_analysis_page, name='ml_analysis'),
    path('export/accidents/', views.export_accidents_excel, name='export_accidents_excel'),
    path('export/events/', views.export_events_excel, name='export_events_excel'),
    path('district-report/', views.district_report, name='district_report'),
    path('api/accidents/search/', views.api_accidents_search, name='api_accidents_search'),
    path('api/accidents/tags/', views.api_accidents_tags, name='api_accidents_tags'),
]
